apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: dev01
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
