apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80    # External service port
      targetPort: 8080  # Spring Boot application port
  type: LoadBalancer  # Change to NodePort or ClusterIP as needed
